### ISSUE TITLE
[Bug] Local network addresses hardcoded to 192.168.0.0/16

### ISSUE THREAD

**Issue by precla** [corrad1nho/qomui#14]
Private networks can have the following IP ranges:
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16

qomui is currently hardcoded to the last one. Fortunately, this is the most used. Unfortunately, someone with 
one of the other IP ranges will have a hard time connecting.

There are two options now:
1. Hardcode those two ranges too (easy)
2. Check what IP range the client is in and according to the result, set only that range in the firewall

Source:
[Wikipedia Private Network](https://en.wikipedia.org/wiki/Private_network)

(I'm not sure if this can count as a 'bug'...)

**Comment by corrad1nho** [comment]
I agree that the current solution is not optimal even though firewall rules are editable via the options tab (this would also be a short-term fix for anyone running into this issue). Between the two solutions you propose I tend towards the first one as this is - as you say - a lot easier to implement and thus more robust.
