### ISSUE TITLE
[Feature] Secondary VPN connection to dedicated to a specific application

### ISSUE THREAD

**Issue by ripkennu420** [corrad1nho/qomui#2]
Adding a way in the GUI to connect a secondary VPN connection to dedicated to a torrent client. Freeing up bandwidth in the other connection/s. This is something that can be hacked with iptables but is very useful and is absent in network managers ive seen. This helps if one wants to streaming media and actively downloading and seeding ubuntu iso's at full speeds.

**Comment by corrad1nho** [comment]
The bypass-feature is a good starting point for this as it has its own routing table. I haven't tried this but I guess running OpenVPN in bypass mode could theoretically work as long as routes are set manually.

**Comment by corrad1nho** [comment]
It took me a while to figure out how to do that and many, many failed attempts to get it working with most other features. But voilà release 0.7.1 finally features an experimental implementation for secondary VPN connections. I will close this issue, but you are always welcome to open new ones for further suggestions or bug reports.
