### ISSUE TITLE
Add option to disable compression.

### ISSUE THREAD

**Issue by brainscar** [corrad1nho/qomui#22]
Thank you for your hard work.

My suggestion is related to this: 

- https://old.reddit.com/r/VPN/comments/96zthc/blackhat_2018_vpn_padding_oracle_attack_for_all/

- http://i.blackhat.com/us-18/Wed-August-8/us-18-Nafeez-Compression-Oracle-Attacks-On-Vpn-Networks.pdf

**Comment by corrad1nho** [comment]
Unfortunately, this is something that is set by the provider (server-side configuration). Via the modify button Qomui offers an option to change the client-side OpenVPN configuration such as setting "comp-lzo no". I just tried that with one provider (ProtonVPN) that uses lzo compression. Long story short: Overriding the compression setting client-side will break the connection - OpenVPN continously spews error messages: "Bad compression stub decompression header byte". Similarly, if you remove the "comp-lzo" option, OpenVPN will also complain: "write to TUN/TAP : Invalid argument (code=22)". 

So I assume that you cannot force compression settings from a client. Or am I missing something?

**Comment by brainscar** [comment]
Hi corrad1nho! Thank you so much, you are completely correct. I did not know this before you explained it. Thank you again for your hard work. Feel free to close this.
