### ISSUE TITLE
support Firewalld for ufw

### ISSUE THREAD

**Issue by 2tbwXj46BDbdNBRV79DS** [corrad1nho/qomui#23]
Having problems with the firewall option. Seems to not block anything. Probably to do with firewalld. similar to the problem with ufw. 

heres some info on setting up firewalld killswitch going to test and see if i can get it to work
https://forums.fedoraforum.org/showthread.php?311476-How-can-I-do-Internet-Kill-Switch-for-VPN-on-Fedora/page3
may run in to issues with bypass and hop features with this.

**Comment by corrad1nho** [comment]
I just tested the firewall on Fedora 28 and I think I found the issue: Indeed, Qomui's firewall is overridden by firewalld on startup. Qomui is designed to be "always-on" meaning it's firewall is always active. In that case the best choice is to disable firewalld as the Fedora implementation seems to flush existing rules. If you don't want to do that: You can also choose to only start qomui's firewall when the gui is active via the "Configure firewall" menu. That should work, too. Thanks for bringing that to my attention!

**Comment by corrad1nho** [comment]
Here is what I will try to do: Implement a check that issues a warning if ufw or firewalld are activated and offer an option to disable those.
