### ISSUE TITLE
Add shadowsocks client functionality

### ISSUE THREAD

**Issue by baimafeima** [corrad1nho/qomui#25]
Would you consider adding shadowsocks client functionality to connect to a shadowsocks server, similar to what is offered with `shadowsocks-qt5`? 
See: https://github.com/shadowsocks/shadowsocks-qt5
In some countries OpenVPN is detected and blocked in real-time through deep-packet inspection and having a possibility - in such cases - to switch to a shadowsocks server (one can easily install a private shadowsocks server via a Streisand script running on a VPS, thereby complementing the offerings of commercial VPN providers) would be great.

**Comment by corrad1nho** [comment]
Yes, that's a very good suggestion. I don't have a server right now, so implementing and testing this is a bit difficult, but I'm planning to get one. As far as I understand, adding shadowsocks to a commercial or non-commercial OpenVPN connection is not that hard, is it?

**Comment by corrad1nho** [comment]
See #31
