### ISSUE TITLE
[Feature requestest]Double hop on cli 

### ISSUE THREAD

**Issue by skyerjoe** [corrad1nho/qomui#29]
Is it planned to integrate a way the double vpn feature with open vpn on cli ?

Regards

**Comment by corrad1nho** [comment]
This is already implemented: You can doublehop via cli by using the -v argument:

``

**Comment by skyerjoe** [comment]
But not with open vpn or ?

**Comment by corrad1nho** [comment]
No, as via Gui OpenVPN over SSL/SSH is not supported in double-hop mode.

**Comment by skyerjoe** [comment]
Sorry corrad 

I have to be sure that i understand this correctly cause im not so firm with this.

You mean the connection with the config. ewhich will be established over vpn.
And these ones, doesnt work with an  ssl server entry.
Am i correct ? 

Regards

**Comment by corrad1nho** [comment]
OpenVPN over SSL/SSH atm exclusively works with AirVPN and WIndscribe. This is a specific feature by both those providers to cloak the OpenVPN tunnel. All "normal" OpenVPN configs via UDP and TCP will work with doublehop. If you are using one of the above providers just don't set port/protocol to SSL or SSH if you want to use doublehop.

**Comment by skyerjoe** [comment]
Thnx for clearing 

Regards
