### ISSUE TITLE
Wireguard does not work

### ISSUE THREAD

**Issue by klemy** [corrad1nho/qomui#30]
I am on Ubuntu 18.04 and I try to connect to a WIreGuard server.

The loading bar is infinite, here is the error message from the QOMUI Service Logs :
```
WireGuard: wg-quick: `/usr/share/qomui/wg_qomui.conf' does not exist
```

**Comment by corrad1nho** [comment]
I'm so sorry that it took me a while to publish a new release where this bug is finally fixed.
