### ISSUE TITLE
Minimize & Tray Icon

### ISSUE THREAD

**Issue by armaccloud** [corrad1nho/qomui#35]
Hi,
I am encountering some issues with the minimize option on elementaryos Juno.

- The option to start minimized doesn't function (it opens the GUI)
- When I click the X and choose Minimize, it removes the icon in the tray (however the wireguard connection remains active.

![screenshot from 2018-10-20 10-48-19](https://user-images.githubusercontent.com/9272078/47253674-b6908280-d456-11e8-9176-2e6725506d3e.png)
![screenshot from 2018-10-20 10-54-49](https://user-images.githubusercontent.com/9272078/47253676-bb553680-d456-11e8-9b92-906e8192324b.png)

OS: ElementaryOS 5.0 (Juno)
Qomui Version 0.7.4

**Comment by corrad1nho** [comment]
Have never tried Qomui on ElementaryOS. I'll look into the minimize function but it's quite hard to get it right for all available DEs.

**Comment by armaccloud** [comment]
That is great you want to look into it. The way to reproduce would be

- Installation of the new elementaryos 5.0 Juno
- Followed [these steps](https://elementaryos.stackexchange.com/questions/16502/missing-icons-in-the-wingpanel/16503#16503) to enable application tray icons
- Installed Qomui
- Verify the minimize option doesn't keep the tray icon

Thanks!

**Comment by mdl054** [comment]
I can confirm the same behavior happens on Fedora 28 and on Arch, both using Gnome with or without Topicons plus.

**Comment by corrad1nho** [comment]
One thing I forgot to mention: If you use the minimize option on DEs that don't support a system tray the application will just disappear with no way of retrieving it. This will be fixed!

**Comment by corrad1nho** [comment]
The solution implemented in v0.8.0 is to remove the minimize option in the exit dialog if no tray is available or detected. Alternatively, there is now an option to show/hide the application window via the tray icon menu.

**Comment by corrad1nho** [comment]
I've never tested with i3/polybar. The minimize option actually hides the window and can only be activated again via the tray icon. In your case I would suggest not using the minimize option, it doesn't make sense with the way i3 works anyway, does it?
