### ISSUE TITLE
Problems Connect to Custom VPN Services

### ISSUE THREAD

**Issue by Fluke667** [corrad1nho/qomui#38]
**Problems Connect to safervpn.com**

This is the Original *.ovpn file (without certificate)

`
client
dev tun
proto udp
cipher AES-256-CBC
remote-cert-tls server
remote de1.safervpn.net 1194 # - Your server IP and OpenVPN Port
resolv-retry infinite
nobind
tun-mtu 1500
tun-mtu-extra 32
mssfix 1450
persist-key
persist-tun
auth-user-pass
comp-lzo
verb 3
`

After Adding to Qomui 2 lines changed in /usr/share/qomui/:

`
remote 146.0.42.22 1194
auth-user-pass /usr/share/qomui/certs/safervpn.com-auth.txt
`

and on connect it creates a temp.ovpn file looks like this (only changed lines):

`
proto #
`

Log gives me this Error:

> 2018-10-28 12:09:15,533 - INFO - OpenVPN:Options error: Unrecognized option or missing or extra parameter(s) in /usr/share/qomui/safervpn.com/temp.ovpn:3: proto (2.4.0)

proto udp is correct why Qomui change the line to proto # ???

.
.
.
.
.

**Qomui Testing Status:**
> nordvpn.com - Works with Qomui
> ibvpn.com - Works with Qomui
> tunnelbear.com - Works with Qomui
> airvpn.org - Works with Qomui
> ipvanish.com - Works with Qomui
> protonvpn.com - Works with Qomui
> safervpn.com - Works with Qomui
> hidemyass.com - Works with Qomui
> cactusvpn.com - Works with Qomui
> purevpn.com - Problems with Connecting
> goldenfrog.com - Works with Qomui
More VPN Services coming soon...

**Comment by Fluke667** [comment]
it worked with the "Override Settings from the Config File"
I have Choosen there UDP an Port 1194

Now it works :)

**Comment by Fluke667** [comment]
**hidemyass.com Problems Solved...**

HideMyAss Official *.ovpn Configs works only if you disable IPv6 in Qomui Options

**Comment by Fluke667** [comment]
**purevpn.com Problems with Certificate**

OpenVPN: WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.

**Comment by Fluke667** [comment]
Yeah goldenfrog.com works with Qomui :)

**Comment by corrad1nho** [comment]
Thanks a lot for testing all those providers! 

**purevpn.com Problems with Certificate**
That is an issue with the OpenVPN config files provided by PureVPN. 

**Problems Connect to safervpn.com**
Config file looks poorly formatted to me. Each option should be on a new line. Proto line must be "udp" or "tcp". Qomui does alter config files slightly after importing such as resolving hostnames. I'd need to see the original config file provided by safervpn to investigate the issue.

**Comment by corrad1nho** [comment]
Thanks again for testing all those providers with Qomui.
