### ISSUE TITLE
Freeze on ubuntu

### ISSUE THREAD

**Issue by bipox** [corrad1nho/qomui#39]
Hi,

Thank you for the program, it works great (in arch) and was much needed!

I have the AUR version installed in KDE Manjaro, and it works perfectly.

The .deb version in KDE Neon freezes after I connect to a server.
A window opens and the program stops responding. The connection to the server works.
[This](https://ncloud.zaclys.com/index.php/apps/files_sharing/ajax/publicpreview.php?x=1920&y=592&a=true&file=qomui%2520freeze.png&t=y9pQyGgsgoMttnP&scalingup=0) is what I see.

I use ProntonVPN.

edit: do NOT freeze using Windscribe

so AUR + ProtonVPN: ok
deb + ProtonVPN: freeze
deb + Windscribe: ok

edit2: after adding windscribe everything works for some reason.

**Comment by bipox** [comment]
I'm reopening the issue because I'm experiencing the same problem on a second machine (KDE Neon too) and this time it won't go away.

I'm using the flatpak version.

This program is amazing, I'm surprised it isn't more popular. I don't see much activity - i hope you won't abandon it!

**Comment by corrad1nho** [comment]
I haven't had much time lately to work on Qomui, but I won't abandon it. I'm currently working on a new update. Where did you get a flatpak version of Qomui? I haven't created a flatpak for Qomui. 

About those freezes: Do you have libnotify installed on your system?

**Comment by bipox** [comment]
That's good to hear!

Sorry I've got this mixed up with some other software, and indeed I didn't install yours through flatpak.

I have libnotify4 installed.

**Comment by corrad1nho** [comment]
Can you test the following command from your terminal? You should see a desktop notification. 
`notify-send "test" "test" --icon=dialog-question
`

**Comment by bipox** [comment]
It prompted me to install libnotify-bin
Problem solved.

Which is strange since I had the same issue on the other computer and don't remember installing libnotify on it. Maybe it came with another software I installed later?

Anyway, thanks
