### ISSUE TITLE
My Feature Requests

### ISSUE THREAD

**Issue by Fluke667** [corrad1nho/qomui#40]
**Map with VPN Locations**
Better if we can Turn On/Off this Feature

**Internet Kill Switch**
Only Access Internet with VPN Connection

**App Kill Switch**
Apps to kill if Connection drops

**Change VPN Periodically**
Good if we can set a time how often it should change - Random/Selected

**Whitelist/Blacklist VPN Servers**

**Ip Adress Checker**
Dropdown Menu with some Services to Check IP for Anonymity

Example https://i.imgur.com/0KJW0GY.png

Services suggested for IP Adress Checker:
https://whoer.net/ <<< Anonymity, Blacklist
https://ip-lookup.net <<< Basic IP informations
https://whatismyipaddress.com
https://whatismyip.com
https://tracemyip.org

**Comment by precla** [comment]
iirc, "Internet Kill Switch" -> already exists as "Activate Firewall" which can block connections outside VPN

**Comment by corrad1nho** [comment]
I'll close this issue for now. The ability to change vpns periodically might be added to the new profiles feature in one of the next updates.
