### ISSUE TITLE
How this work in Ubuntu

### ISSUE THREAD

**Issue by dosenfleisch** [corrad1nho/qomui#42]
First thanks so much for creating this.  For someone like yourself to come up with this puts to shame whomever is maintaining Network Manager given how long Ubuntu's DNS leak problem has been an ongoing pain.  My solution to that problem (one I found on youtube) was once gnome openvpn networkmanager plugin was installed, I did an apt-get install openresolv nscd unbound.  If I tried Qomui on top of this, no go, the system slows to a crawl, goes dark and freezes.

I've tried NordVPN's config file, filtering out the TCP files, on Qomui for:
1.  Ubuntu 16.04LTS.  On a fresh install, a longer running install with every offering you've packaged and in now way can I get this thing to work.  
2.  Ubuntu 18.04LTS.  On this distro, it works.  Sometimes it takes a couple cracks to get the folder to be recognized, but once it has, it's good to go.  
3.  PopOS!  Absolutely no go on this one.  I don't know why.
4.  OpenSUSE Leap15.  It works here, but no themepack would change the appearance of the gui.  No icons in the taskbar.  

If I'd know I could actually report these things to you, I'd have copied logs and reported them to you.  Right now, I'm back to my original 16.04 distro, with the Youtube solution to dnsleaks.  

Thanks and best of luck.  A reliable OpenVPN gui has long been needed.

**Comment by dosenfleisch** [comment]
On Ubuntu 16.04, when I said doesn't work, if you can get the app to import the files, it won't connect.  An error pops up and I'm sorry I'm not much help here today, but the pop up is immediate and definite.
On Ubuntu 18.04, what I meant was that on the Provider tab, filling in the user name, password and setting the appropriate folder takes sometimes two tries before a successful connection can be made.  I've tried setting the folder first, then the name and pword, or the name and pword first then the folder.  It works or doesn't work regardless the order of entry I use.
PopOS!  This is a distro that the folks at System76 have cooked up based on Ubuntu 18.04 and lately, they've brought out an 18.10 version.  System76 custom build desktops and laptos expressly for their PopOS! distro, but previously were only supporting Ubuntu distros.  On PopOS! the install succeeded, but the app froze.  No import nothing.  

I realize my accounting of my experiences are a bit sketchy, but I was seeking a distro that could handle Qomui and still satisfied my need for a rock solid OS.  So far, only 16.04 satisfies the latter, but once I set up networkmanager with openresolv nscd unbound, and you fail at getting Qomui to work, removing Qomui messes up the openresolv nscd unbound fix I used to solve DNS leaks, and Networkmanager is back to leaking again.  At this point I don't know what to do other than start from scratch and reinstall everything.  

At present I am not having much luck with a graphics hardware problem with the folks at System76 who it seems have not been taking me or my complaint that a hardware problem exists seriously since I bought the machine nearly a year and a half ago.  So for now, I can't get back into a concerted effort to answer all your questions or provide you with anything useful until that is resolved.  I bought this box to experiment and learn Linux.  But I've been locked to Ubuntu because that's all they will support and as it would appear, not much else either.

**Comment by corrad1nho** [comment]
>  An error pops up and I'm sorry I'm not much help here today, but the pop up is immediate and definite.

Check if libnotify is installed correctly. You can test from your terminal with the following command:
`notify-send "test" "test" --icon=dialog-question  `

> On Ubuntu 18.04, what I meant was that on the Provider tab, filling in the user name, password and setting the appropriate folder takes sometimes two tries before a successful connection can be made. I've tried setting the folder first, then the name and pword, or the name and pword first then the folder. It works or doesn't work regardless the order of entry I use.

The order of setting folder, name, password doesn't matter at all. But importing and connecting to a imported servers a two different things. If you have been able to establish a connection, the import was successful, wasn't it? If the connection fails, I'd need the logs. Another thing you can try is testing your config file directly with openvpn:
`openvpn /your/config/file.conf`

> On PopOS! the install succeeded, but the app froze. No import nothing.

Again, check if libnotify is installed. Or does it freeze instantly, i.e. you are not able to use the gui at all?

> o far, only 16.04 satisfies the latter, but once I set up networkmanager with openresolv nscd unbound, and you fail at getting Qomui to work, removing Qomui messes up the openresolv nscd unbound fix I used to solve DNS leaks, and Networkmanager is back to leaking again.

Although I've not tested that extensively, Qomui should generally work with DNS resolvers such as unbound. By default, Qomui tries to set the DNS server from your provider in /etc/resolv.conf systemwide. You can override this behavior by setting alternative DNS servers in the options tab. Apart from modifying resolv.conf Qomui won't mess with any other DNS-related configurations as long as you don't use the bypass feature which requires dnsmasq.

**Comment by corrad1nho** [comment]
No answer for nearly a month, so I will close this issue. I've tested the latest release on a fresh installation of Ubuntu 18.10 and it works fine. Feel free to re-open it or open a new one and I'll gladly help you resolve your issue.
