### ISSUE TITLE
Where is the auto-download configs code in repo?

### ISSUE THREAD

**Issue by brainscar** [corrad1nho/qomui#45]
Can't find the auto-fetch protonvpn config code in this repo.

**Comment by corrad1nho** [comment]
Are you looking for the option or the code? You can auto-download current ProtonVPN configs from the provider tab. It's pretty self-explanatory I hope. The code itself is in qomui/update.py.

**Comment by brainscar** [comment]
Ah, update.py, I can't believe I overlooked that. Thank you so much. Amazing software by the way, thank you!

**Comment by corrad1nho** [comment]
Thanks!
