### ISSUE TITLE
Problems with qomui service

### ISSUE THREAD

**Issue by sleepingspy999** [corrad1nho/qomui#48]
Trying to install on latest version but the qomui service gives errors and wll not start.
Any help would be appreciated.

● qomui.service - qomui
   Loaded: loaded (/lib/systemd/system/qomui.service; enabled; vendor preset: di
   Active: failed (Result: exit-code) since Sun 2018-12-16 12:49:34 GMT; 8s ago
  Process: 4245 ExecStart=/usr/bin/env qomui-service (code=exited, status=1/FAIL
 Main PID: 4245 (code=exited, status=1/FAILURE)

Dec 16 12:49:33 sleeper env[4245]:   File "/usr/lib/python3/dist-packages/pkg_re
Dec 16 12:49:33 sleeper env[4245]:     ws.require(__requires__)
Dec 16 12:49:33 sleeper env[4245]:   File "/usr/lib/python3/dist-packages/pkg_re
Dec 16 12:49:33 sleeper env[4245]:     needed = self.resolve(parse_requirements(
Dec 16 12:49:33 sleeper env[4245]:   File "/usr/lib/python3/dist-packages/pkg_re
Dec 16 12:49:33 sleeper env[4245]:     raise DistributionNotFound(req, requirers
Dec 16 12:49:33 sleeper env[4245]: pkg_resources.DistributionNotFound: The 'qomu
Dec 16 12:49:34 sleeper systemd[1]: qomui.service: Main process exited, code=exi
Dec 16 12:49:34 sleeper systemd[1]: qomui.service: Failed with result 'exit-code
Dec 16 12:49:34 sleeper systemd[1]: Failed to start qomui.

**Comment by sleepingspy999** [comment]
Using Kali linux with KDE

**Comment by sleepingspy999** [comment]
qomui.service - qomui
   Loaded: loaded (/lib/systemd/system/qomui.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2018-12-16 13:01:11 GMT; 2min 7s ago
  Process: 5616 ExecStart=/usr/bin/env qomui-service (code=exited, status=1/FAILURE)
 Main PID: 5616 (code=exited, status=1/FAILURE)

Dec 16 13:01:11 sleeper env[5616]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 581, in _build_master
Dec 16 13:01:11 sleeper env[5616]:     ws.require(__requires__)
Dec 16 13:01:11 sleeper env[5616]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 898, in require
Dec 16 13:01:11 sleeper env[5616]:     needed = self.resolve(parse_requirements(requirements))
Dec 16 13:01:11 sleeper env[5616]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 784, in resolve
Dec 16 13:01:11 sleeper env[5616]:     raise DistributionNotFound(req, requirers)
Dec 16 13:01:11 sleeper env[5616]: pkg_resources.DistributionNotFound: The 'qomui==0.8.0' distribution was not found and is required by the applicati
Dec 16 13:01:11 sleeper systemd[1]: qomui.service: Main process exited, code=exited, status=1/FAILURE
Dec 16 13:01:11 sleeper systemd[1]: qomui.service: Failed with result 'exit-code'.
Dec 16 13:01:11 sleeper systemd[1]: Failed to start qomui.

**Comment by corrad1nho** [comment]
Glad it's working now!
