### ISSUE TITLE
Qomui not working anymore, KDE Neon 14.4

### ISSUE THREAD

**Issue by bipox** [corrad1nho/qomui#53]
I'm really sorry to post here again, but Qomui stopped working and I can't fix it. It seems to be a python issue.

```
qomui-gui
Icon theme "gnome" not found.
QLayout: Attempting to add QLayout "" to QomuiGui "Form", which already has a layout
Traceback (most recent call last):
  File "/usr/bin/qomui-gui", line 11, in <module>
    load_entry_point('qomui==0.8.0', 'gui_scripts', 'qomui-gui')()
  File "/usr/lib/python3.6/dist-packages/qomui/qomui_gui.py", line 2775, in main
    ex = QomuiGui()
  File "/usr/lib/python3.6/dist-packages/qomui/qomui_gui.py", line 165, in __init__
    self.qomui_service.disconnect("main")
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.79 was not provided by any .service files
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/var/crash/_usr_bin_qomui-gui.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/qomui-gui", line 11, in <module>
    load_entry_point('qomui==0.8.0', 'gui_scripts', 'qomui-gui')()
  File "/usr/lib/python3.6/dist-packages/qomui/qomui_gui.py", line 2775, in main
    ex = QomuiGui()
  File "/usr/lib/python3.6/dist-packages/qomui/qomui_gui.py", line 165, in __init__
    self.qomui_service.disconnect("main")
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.79 was not provided by any .service files
```

KDE Frameworks 5.53.0
Qt: 5.11.2
Kernel: 4.19.8

**Comment by corrad1nho** [comment]
Could you check if the background process is running properly via "systemctl status qomui" and post the output here?

**Comment by bipox** [comment]
sure

```
 systemctl status qomui
● qomui.service - qomui
   Loaded: loaded (/lib/systemd/system/qomui.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2018-12-30 14:15:45 CET; 1 day 2h ago
  Process: 1506 ExecStart=/usr/bin/env qomui-service (code=exited, status=1/FAILURE)
 Main PID: 1506 (code=exited, status=1/FAILURE)

déc. 30 14:15:45 remi-XPS-13-9360 env[1506]:     BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
déc. 30 14:15:45 remi-XPS-13-9360 env[1506]:   File "/usr/lib/python3.6/logging/handlers.py", line 57, in __init__
déc. 30 14:15:45 remi-XPS-13-9360 env[1506]:     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
déc. 30 14:15:45 remi-XPS-13-9360 env[1506]:   File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
déc. 30 14:15:45 remi-XPS-13-9360 env[1506]:     StreamHandler.__init__(self, self._open())
déc. 30 14:15:45 remi-XPS-13-9360 env[1506]:   File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
déc. 30 14:15:45 remi-XPS-13-9360 env[1506]:     return open(self.baseFilename, self.mode, encoding=self.encoding)
déc. 30 14:15:45 remi-XPS-13-9360 env[1506]: FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/usr/share/qomui/qomui.log'
déc. 30 14:15:45 remi-XPS-13-9360 systemd[1]: qomui.service: Main process exited, code=exited, status=1/FAILURE
déc. 30 14:15:45 remi-XPS-13-9360 systemd[1]: qomui.service: Failed with result 'exit-code'.
```

**Comment by corrad1nho** [comment]
Which python version is installed on your system? 
`python3 -V`

It seems that Qomui has been installed for Python 3.6 and this may not be the correct version for your system.

**Comment by corrad1nho** [comment]
Actually, I suspect there might be an issue with the Debian packages. On one of my testing installations /usr/share/qomui was deleted, too, after upgrading Qomui. I'll have to look into that further. In the meanwhile, removing and then reinstalling Qomui should solve this. Thanks a lot for letting me know!

**Comment by bipox** [comment]
That did it, thanks!

**Comment by bipox** [comment]
I had qomui-service stop again, suddenly (I wasn't doing anything special, computer running for a long time)

A reboot fixed it.

**Comment by bipox** [comment]
I use Protonvpn (plus) and sometimes windscribe (although windscribe subscription just expired I believe).

I have auto-update activated on both devices.

I did click on "restart qomui-service", it didn't work the first time (reconnect to a vpn wouldn't work), the second time it did work but I had the connection switched from wifi to ethernet.

The computer without wifi adapter has no issue.

I'll post the console output on next crash

**Comment by corrad1nho** [comment]
Windscribe auto-update doesn't work properly at the moment, unfortunately. This will be fixed in the next release. ProtonVPN shouldn't produce any errors (I have a subscription with them myself and test it regularly). I'll try switching from wifi to ethernet on my notebook once I get the chance to see if there is any issue. 

Can you try deactivating auto-update to check if this causes the crashes?

**Comment by bipox** [comment]
I disabled auto update, no crash for a week. Upon reenabling it, crash.

I am now keeping auto update ON but removed Windscribe as a provider: no crash yet.

**Comment by corrad1nho** [comment]
Yes, unfortunately Windscribe auto-update is broken. It uses the wrong credentials that's why its failing. I'm still trying to figure out why it crashes in some instance while in other cases it just returns an error message. I have already implemented a solution that will fix the general issue and be part of the next release.

**Comment by bipox** [comment]
I don't use windscribe anymore, just reporting since I'm not sure what is relevant and what isn't  :smile: 

And you're already on it, great!

**Comment by corrad1nho** [comment]
It's finally fixed in v0.8.2.

**Comment by corrad1nho** [comment]
Yes, unfortunately removing and installing qomui again is required one last time. I'm sorry.

**Comment by bipox** [comment]
Works perfectly now, thank you.
