### ISSUE TITLE
Multihopping not always working. Mullvad

### ISSUE THREAD

**Issue by foNYWZc** [corrad1nho/qomui#55]
So first thing's first; I love the project and am very thankful for its development! Keep up the great work so far.

I seem to be having issues with multihopping. It seems to only work with certain servers and it's impossible to tell which servers those are. So I have my protocol set to UDP 1194.

Sometimes when I set a hop server and than connect to the secondary server it works flawlessly. I'll see the Hop server has something like TCP 80 and the other server has 1194 like I have it set to. This works no problem. But other times I'll do the same thing and my non-hop server will be at UDP 1194 like it should but the hop server is also set to UDP 1194, when this happens the hop is not done correctly and my internet will just work as if I had only connected to the server I dedicated as the hop server.

So if I go Sweden (Hop) US (Non-Hop) traffic will think i'm going through Sweden.
Is this cause I auto downloaded the mullvad configs? Should I download the configs manually and select TCP:80 for the servers I want to use as hops and UDP:1194 for the ones I want to connect to?

Thanks in advanced!

**Comment by corrad1nho** [comment]
Are both servers from Mullvad? If so, both hops should use the same port and protocol (as set via the provider tab). Generally, I recommend UDP for double hop. How do you know that port and protocol are different? Can you tell me which server combinations work and which do'nt, so I can test?

**Comment by corrad1nho** [comment]
Quite true, double hop will fail if you include a proxy in the config file. As a workaround you could try adding some Mullvad servers manually and use those as second hops. I have actually never tried if this works. Making double hop more flexible (including supporting WireGuard) is on my to-do list. But it may take some time to implement that. I hope you'll understand!
