### ISSUE TITLE
Issues with AirVPN credentials.

### ISSUE THREAD

**Issue by concepthf** [corrad1nho/qomui#58]
When it imports AirVPN configs, it says there is an issue with the credentials but the login is correct. 
![screenshot_20181231_153313](https://user-images.githubusercontent.com/18093789/50569032-74ff3c00-0d11-11e9-859b-dc907fe79133.png)

**Comment by corrad1nho** [comment]
I'm sorry, this is a bug. Expect an update very soon. In the meantime the workaround is to import Airvpn config files manually.

**Comment by corrad1nho** [comment]
Please install the latest release. It should work now.
