### ISSUE TITLE
Windscribe Errors (0.8.2)

### ISSUE THREAD

**Issue by Kastilo** [corrad1nho/qomui#68]
OS: Kubuntu 18.10
Qomui-GUI: 0.8.1
Provider: Windscribe

Hello, it seems that the option for bypass fails, because I am unable to use anything outside of the current connection (Switzerland when I want to use USA or just my actual connection) for a few applications while keeping the rest protected.

**Comment by corrad1nho** [comment]
Hi Kastilo, could you provide me with more information? Please set logging to debug (in the log tab) and post the log. Furthermore, make sure that the following packages are installed on your system:  cgroup-lite & cgroup-tools.

**Comment by Kastilo** [comment]
Hello,
Seems after the initial issue, it has stopped, not sure why since this kept persisting after restarts but suddenly it's fine?
It would give an error of "w0lan bypass" created instead of the now "Started Firefox Web Browser in bypass" so I'm not sure what went wrong, especially since this is a fresh install and I had restarted a few times before I noticed this issue. Sorry to bother you

**Comment by corrad1nho** [comment]
Does it work now or does it not? If not, please post the log so I can see if the bypass has been configured correctly.

**Comment by Kastilo** [comment]
It works now it seems. However, not it has become the issue with the new version

"2019-02-02 23:15:01,927 - INFO - OpenVPN: VERIFY KU OK
2019-02-02 23:15:01,928 - INFO - OpenVPN: Validating certificate extended key usage
2019-02-02 23:15:01,928 - INFO - OpenVPN: ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
2019-02-02 23:15:01,928 - INFO - OpenVPN: VERIFY EKU OK
2019-02-02 23:15:01,929 - INFO - OpenVPN: VERIFY OK: depth=0, C=CA, ST=ON, O=Windscribe Limited, OU=Operations, CN=Windscribe Node Server 4096
2019-02-02 23:15:04,363 - INFO - OpenVPN: Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
2019-02-02 23:15:04,363 - INFO - OpenVPN: [Windscribe Node Server 4096] Peer Connection Initiated with [AF_INET]31.7.57.242:80
2019-02-02 23:15:05,372 - INFO - OpenVPN: SENT CONTROL [Windscribe Node Server 4096]: 'PUSH_REQUEST' (status=1)
2019-02-02 23:15:05,715 - INFO - OpenVPN: AUTH: Received control message: AUTH_FAILED
2019-02-02 23:15:05,716 - INFO - OpenVPN: SIGTERM[soft,auth-failure] received, process exiting
2019-02-02 23:15:05,716 - INFO - Authentication error while trying to connect
2019-02-02 23:15:05,717 - INFO - OpenVPN:
2019-02-02 23:15:05,717 - INFO - OpenVPN:
2019-02-02 23:15:05,722 - INFO - OpenVPN - process killed
2019-02-02 23:15:05,735 - WARNING - Desktop notifications not"

"kastilo@RED-OS:~$ sudo apt purge qomui          
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  dnsmasq ktorrent-data libkf5plotting5 libkf5syndication5 libkf5webkit5 libktorrent-l10n
  libktorrent6 libpkcs11-helper1 net-tools openvpn python3-bs4 python3-html5lib python3-lxml
  python3-psutil python3-webencodings stunnel4
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  qomui*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 3,824 kB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 245707 files and directories currently installed.)
Removing qomui (0.8.2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-3ubuntu3) ...
Processing triggers for dbus (1.12.10-1ubuntu2) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
(Reading database ... 245548 files and directories currently installed.)
Purging configuration files for qomui (0.8.2) ..."

"kastilo@RED-OS:~$ sudo apt-get install qomui
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  dnsmasq libpkcs11-helper1 net-tools openvpn python3-bs4 python3-html5lib python3-lxml
  python3-psutil python3-webencodings stunnel4
Suggested packages:
  resolvconf easy-rsa python3-genshi python3-lxml-dbg python-lxml-doc python-psutil-doc
  logcheck-database
The following NEW packages will be installed:
  dnsmasq libpkcs11-helper1 net-tools openvpn python3-bs4 python3-html5lib python3-lxml
  python3-psutil python3-webencodings qomui stunnel4
0 upgraded, 11 newly installed, 0 to remove and 0 not upgraded.
Need to get 3,080 kB/6,113 kB of archives.
After this operation, 17.1 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://us.archive.ubuntu.com/ubuntu cosmic/universe amd64 stunnel4 amd64 3:5.44-1ubuntu4 [151 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu cosmic/universe amd64 dnsmasq all 2.79-1 [16.2 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu cosmic/main amd64 libpkcs11-helper1 amd64 1.25.1-1 [44.4 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu cosmic/main amd64 net-tools amd64 1.60+git20161116.90da8a0-2ubuntu1 [197 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu cosmic/main amd64 openvpn amd64 2.4.6-1ubuntu2 [473 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu cosmic/main amd64 python3-bs4 all 4.6.3-1 [71.5 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu cosmic/main amd64 python3-webencodings all 0.5-2 [10.4 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu cosmic/main amd64 python3-html5lib all 1.0.1-1 [84.2 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu cosmic/main amd64 python3-lxml amd64 4.2.5-1 [1,894 kB]
Get:10 http://us.archive.ubuntu.com/ubuntu cosmic/main amd64 python3-psutil amd64 5.4.6-1build1 [138 kB]
Fetched 3,080 kB in 1s (2,831 kB/s)      
Preconfiguring packages ...
Selecting previously unselected package stunnel4.
(Reading database ... 244847 files and directories currently installed.)
Preparing to unpack .../00-stunnel4_3%3a5.44-1ubuntu4_amd64.deb ...
Unpacking stunnel4 (3:5.44-1ubuntu4) ...
Selecting previously unselected package dnsmasq.
Preparing to unpack .../01-dnsmasq_2.79-1_all.deb ...
Unpacking dnsmasq (2.79-1) ...
Selecting previously unselected package libpkcs11-helper1:amd64.
Preparing to unpack .../02-libpkcs11-helper1_1.25.1-1_amd64.deb ...
Unpacking libpkcs11-helper1:amd64 (1.25.1-1) ...
Selecting previously unselected package net-tools.
Preparing to unpack .../03-net-tools_1.60+git20161116.90da8a0-2ubuntu1_amd64.deb ...
Unpacking net-tools (1.60+git20161116.90da8a0-2ubuntu1) ...
Selecting previously unselected package openvpn.
Preparing to unpack .../04-openvpn_2.4.6-1ubuntu2_amd64.deb ...
Unpacking openvpn (2.4.6-1ubuntu2) ...
Selecting previously unselected package python3-bs4.
Preparing to unpack .../05-python3-bs4_4.6.3-1_all.deb ...
Unpacking python3-bs4 (4.6.3-1) ...
Selecting previously unselected package python3-webencodings.
Preparing to unpack .../06-python3-webencodings_0.5-2_all.deb ...
Unpacking python3-webencodings (0.5-2) ...
Selecting previously unselected package python3-html5lib.
Preparing to unpack .../07-python3-html5lib_1.0.1-1_all.deb ...
Unpacking python3-html5lib (1.0.1-1) ...
Selecting previously unselected package python3-lxml:amd64.
Preparing to unpack .../08-python3-lxml_4.2.5-1_amd64.deb ...
Unpacking python3-lxml:amd64 (4.2.5-1) ...
Selecting previously unselected package python3-psutil.
Preparing to unpack .../09-python3-psutil_5.4.6-1build1_amd64.deb ...
Unpacking python3-psutil (5.4.6-1build1) ...
Selecting previously unselected package qomui.
Preparing to unpack .../10-qomui_0.8.2_amd64.deb ...
Unpacking qomui (0.8.2) ...
Setting up python3-webencodings (0.5-2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Setting up python3-lxml:amd64 (4.2.5-1) ...
Processing triggers for desktop-file-utils (0.23-3ubuntu3) ...
Setting up libpkcs11-helper1:amd64 (1.25.1-1) ...
Setting up python3-bs4 (4.6.3-1) ...
Setting up python3-psutil (5.4.6-1build1) ...
Setting up stunnel4 (3:5.44-1ubuntu4) ...
Setting up dnsmasq (2.79-1) ...
Job for dnsmasq.service failed because the control process exited with error code.
See "systemctl status dnsmasq.service" and "journalctl -xe" for details.
invoke-rc.d: initscript dnsmasq, action "start" failed.
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2019-02-02 23:12:03 CST; 12ms ago
  Process: 25268 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=2)
  Process: 25267 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)

Feb 02 23:12:03 RED-OS systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Feb 02 23:12:03 RED-OS dnsmasq[25267]: dnsmasq: syntax check OK.
Feb 02 23:12:03 RED-OS dnsmasq[25268]: dnsmasq: failed to create listening socket for port 53: Address already in use
Feb 02 23:12:03 RED-OS dnsmasq[25268]: failed to create listening socket for port 53: Address already in use
Feb 02 23:12:03 RED-OS dnsmasq[25268]: FAILED to start up
Feb 02 23:12:03 RED-OS systemd[1]: dnsmasq.service: Control process exited, code=exited status=2
Feb 02 23:12:03 RED-OS systemd[1]: dnsmasq.service: Failed with result 'exit-code'.
Feb 02 23:12:03 RED-OS systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
Setting up openvpn (2.4.6-1ubuntu2) ...
Processing triggers for libc-bin (2.28-0ubuntu1) ...
Setting up python3-html5lib (1.0.1-1) ...
Processing triggers for systemd (239-7ubuntu10.6) ...
Processing triggers for man-db (2.8.4-2) ...
Processing triggers for dbus (1.12.10-1ubuntu2) ...
Setting up net-tools (1.60+git20161116.90da8a0-2ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Setting up qomui (0.8.2) ..."

**Comment by corrad1nho** [comment]
There is nothing wrong with your installation it seems. However, you are getting authentication errors from OpenVPN ("AUTH: Received control message: AUTH_FAILED" & "SIGTERM[soft,auth-failure] received, process exiting"). Check if your credentials (username/password) are valid or your subscription has expired. If credentials are correct try removing Windscribe via the provider tab and adding it again. As mentioned in the changelog v0.8.2 changes the directory where Windscribe certificates, configurations and credentials are saved. I implemented some workarounds to ensure compatibility with existing installations but those might not always work reliably. If this doesn't resolve the issue, please set logging to debug (in the options tab) and post the full log here.

**Comment by corrad1nho** [comment]
I'm sorry this is my mistake. Windscribe uses two different sets of credentials and apparently Qomui is using the wrong ones. You can fix that by selecting a windscribe server and use the modify option. Change "auth-user-pass /use/share/qomui/Windscribe/Windscribe-auth.txt" to "auth-user-pass /use/share/qomui/Windscribe/windscribe_userpass.txt". If that doesn't work, edit the config file directly. It's "/usr/share/qomui/Windscribe/openvpn.conf". Sorry again that I missed that, apparently I was too concerned with trying to ensure compatibility with previous releases.

**Comment by Kastilo** [comment]
It's fine, I'll test this out and if it works I'll spread the word via the Windscribe Discord server for those users affected <3
