### ISSUE TITLE
Problem with port 53 during installation. It is "already in use by another application"

### ISSUE THREAD

**Issue by zb35** [corrad1nho/qomui#74]
Hi, during the installation process, there was a problem with dnsmasq, because "the port 53 is already in use by another application", seems like it is DNS for system resolv. Now I can't  establish any connection via Qomui.  Any ideas?

_Originally posted by @zb35 in https://github.com/corrad1nho/qomui/issues/31#issuecomment-464360032_

**Comment by corrad1nho** [comment]
Which distribution are you using and what do you you mean by "during the installation process"? Seems there is another instance of dnsmasq running on your system which may conflict with Qomui (only if you use the bypass feature, though). Can you try killing all dnsmasq processes and start the service again via "sudo systemctl restart qomui"?

**Comment by zb35** [comment]
I used Linux Mint 19.1 for the first try and now I have installed Ubuntu 18.04 and here is the same problem during installation (during extracting .deb package):
`See "systemctl status dnsmasq.service" and "journalctl -xe" for details.
invoke-rc.d: initscript dnsmasq, action "start" failed.
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2019-02-19 23:16:22 EET; 15ms ago
  Process: 14499 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=2)
  Process: 14498 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)

Feb 19 23:16:22 admin-RX systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Feb 19 23:16:22 admin-RX dnsmasq[14498]: dnsmasq: syntax check OK.
Feb 19 23:16:22 admin-RX dnsmasq[14499]: dnsmasq: failed to create listening socket for port 53: Address already in use
Feb 19 23:16:22 admin-RX dnsmasq[14499]: failed to create listening socket for port 53: Address already in use
Feb 19 23:16:22 admin-RX dnsmasq[14499]: FAILED to start up
Feb 19 23:16:22 admin-RX systemd[1]: dnsmasq.service: Control process exited, code=exited status=2
Feb 19 23:16:22 admin-RX systemd[1]: dnsmasq.service: Failed with result 'exit-code'.
Feb 19 23:16:22 admin-RX systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.`

**Comment by corrad1nho** [comment]
dnsmasq is a dependency for Qomui (primarily needed for the bypass feature). I don't quite understand why Qomui's installation would fail because of this. Apparently, the dnsmasq installation routine fails on your system. Can you try installing dnsmasq first ("sudo apt install dnsmasq")?

**Comment by zb35** [comment]
It turns out, I had disabled dnsmasq from the boot. Seems it is an old problem between systemd-resolved and dnsmasq. One of them shoud be disabled. System-resolved listening TCP port 53, obviously bypass need it also. I'll see how to get around this.
