### ISSUE TITLE
[Feature] option to autoconnect service / headless

### ISSUE THREAD

**Issue by Mangoes** [corrad1nho/qomui#8]
Hi,

Please add an option in the gui to set the service to autoconnect on boot (with all of the settings/servers defined in the gui, including auto reconnect, dns, firewall, etc... ).

This way, it would also work on headless servers without running the gui. (it would work to autoconnect on boot like the openvpn service). 

The gui would only be opened to monitor the connection, or change the settings / servers. Changing anything would automatically apply the changes to the service, including for reboots. 

Many thanks for this beautiful app.

**Comment by corrad1nho** [comment]
I'm planning to implement an option to control qomui via cli. In the meantime, if you want qomui to autoconnect on boot, simply make sure qomui.service is enabled, the autoconnect-setting is active and add qomui-gui to your autostart applications.

**Comment by Mangoes** [comment]
But on headless systems (connecting via remote desktop) this doesn't work as I don't think I can add a qt app to something like rc.local to have it start on boot, right?

Or is there another way?

Thanks.

**Comment by corrad1nho** [comment]
Just uploaded new release v0.6.0 - it contains a (rudimentary) cli.

**Comment by Mangoes** [comment]
Thanks a lot !

**Comment by corrad1nho** [comment]
I will close this issue, but of course you are welcome to open another feature request regarding the cli.
