### ISSUE TITLE
[Feature] wireguard support 

### ISSUE THREAD

**Issue by Mangoes** [corrad1nho/qomui#9]
Hi,

Please add wireguard support.

It would also be great if we could mix openvpn and wireguard servers in the chain.

Many thanks.

**Comment by corrad1nho** [comment]
If wireguard becomes more widespread, I'll be thinking about adding it as an option - but as of now, qomui is a frontend/management-tool for openvpn only. Furthermore, I currently have no subscription with a provider that would allow me to test wireguard extensively. Sorry!

**Comment by Mangoes** [comment]
Azirevpn offers free wireguard.

It works in the same way as openvpn ; you download the config files for the servers (so instead of using the openvpn exe with the config file, you use wireguard).

Also, Mullvad which is already in the app uses it, and PIA is currently in the process of adding it too, check their blog).

Wireguard works much better than openvpn (faster : especially on slower cpus where is gives 2x faster throughput ; also it connects immediately, and more stable : especially when roaming between ips and switching between wifi/mobile data and different networks -> mobile or laptop travel).

Openvpn in comparison feels like an old bulky technology. Wireguard is so much better,especially on mobile connections like Android phones or traveling laptops, it's night and day. The Android beta app connections are much more stable than anything openvpn. 

It's not the question if it will become more widespread. It will. It's the future that replaces the old technologies. 

Thanks.

**Comment by corrad1nho** [comment]
Interesting, it sure sounds very promising. Adding support to qomui is unfortunately not as easy as substituting an executable and some config files - but I'll look into it. Just give me some time!

**Comment by Mangoes** [comment]
Great!

Imagine it mixing openvpn, wiregard tunnels... and why not add support for ssh, etc... (some servers only have ssh).

Thanks a lot for your great work. Your app is going to be the corner stone of VPN tools.

**Comment by Mangoes** [comment]
Many thanks !

Is mixing technically not possible, or is it something we will see later ?

**Comment by corrad1nho** [comment]
For now, I focussed on implementing basic wireguard support. I guess openvpn/wireguard multihop should be possible, but for that I have to take a closer look at the inner workings and configuration options of wireguard.

**Comment by corrad1nho** [comment]
For now, double hop will only work with OpenVPN. WireGuard is still experimental and only supported by very few providers. I'll put adding double-hop support for WireGuard on my to-do-list, though.
