### ISSUE TITLE
Qomui crashes 15 minutes after starting => qomui_gui.py (update_check)

### ISSUE THREAD

**Issue by Fluke667** [corrad1nho/qomui#97]
OS: Debian Stretch with KDE Plasma

Qomui crashes 15 minutes after starting as user ... 
/usr/bin/python3 /usr/local/bin/qomui-service is running

```
QLayout: Attempting to add QLayout "" to QomuiGui "Form", which already has a layout
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/qomui/qomui_gui.py", line 2503, in update_check
    provider = self.queue[0]
IndexError: list index out of range
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = python3.5 path = /usr/bin pid = 25408
KCrash: Arguments: /usr/bin/python3.5
KCrash: Attempting to start /usr/lib/x86_64-linux-gnu/libexec/drkonqi from kdeinit
QSocketNotifier: Invalid socket 9 and type 'Read', disabling...
QSocketNotifier: Invalid socket 15 and type 'Read', disabling...
QSocketNotifier: Invalid socket 13 and type 'Read', disabling...
```

**Comment by Fluke667** [comment]
is okay now

**Comment by corrad1nho** [comment]
Hi, I spotted the issue. Have you added your provider configs manually (instead of selecting one of the supported providers)? If yes, please deactivate the auto-update option (it won't do anything anyway in that case).

**Comment by Fluke667** [comment]
i have added airvpn.org manually.

Checked Settings Auto Update is off and it still crashes :((

This is my config.json:
`{"fw_gui_only": 1, "auto_update": 0, "firewall": 1, "alt_dns2": "1.0.0.1", "Airvpn_last": "2019-04-27 17:08:25.934569", "minimize": 1, "airvpn_key": "Default", "block_lan": 0, "preserve_rules": 0, "bypass": 1, "ping": 1, "autoconnect": 1, "alt_dns1": "1.1.1.1", "log_level": "Info", "alt_dns": 1, "ipv6_disable": 0}`

**Comment by Fluke667** [comment]
Okay removed update_check lines now it works :D
